---
- name: Import and run SCAP generated playbook
  import_playbook: harden/ubuntu2204-cis.yml
  tags:
    - scap

- name: Apply Custom Hardening Role
  hosts: localhost
  connection: local
  roles:
    - role: harden
      tags:
        - custom 