---
- name: Pre-hardening backup
  hosts: localhost
  connection: local
  tasks:
    - name: Backup original hosts file
      copy:
        src: /etc/hosts
        dest: /etc/hosts.steelboot-backup
        remote_src: true

- name: Import SCAP CIS Level 1 Server playbook
  import_playbook: roles/harden/tasks/ubuntu2204-cis.yml

- name: Apply Custom Hardening Role
  hosts: localhost
  connection: local
  roles:
    - role: harden

- name: Post-hardening fixes
  hosts: localhost
  connection: local
  tasks:
    - name: Ensure localhost entries in hosts file
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
        state: present
      loop:
        - "127.0.0.1    localhost"
        - "127.0.1.1    {{ ansible_hostname }}" 